### ISSUE TITLE
Extract StreamClient library as a top level repo

### ISSUE THREAD

**Issue by ericbottard** [projectriff/http-gateway#11]
This will provide a way to embed that library in components that need to connect to liiklus (our "streaming gateway") in a way that is compatible with the opinionated way riff has to serialize data.
The code is already [there](https://github.com/projectriff/http-gateway/blob/5bbdebdc6fdf2c0669f79ebf4ee0e9bfcced1f33/pkg/client/client.go), so all that is needed is to chose a name (which will be part of the go module "identity"). Some candidates are
- projectriff/stream-go-client
- projectriff/streaming-gateway-go-client
- projectriff-gateway/go-client

**Comment by markfisher** [comment]
another option: `projectriff/stream-client-go`

**Comment by ericbottard** [comment]
We'll go with `projectriff/stream-client-go`
