### ISSUE TITLE
Decouple gateway from api server

### ISSUE THREAD

**Issue by scothis** [projectriff/http-gateway#2]
The gateway reading state from the API Server is a mixing of the control plane and data plan that should be avoided.

Instead, we could have the controller write a `riff-streams` ConfigMap that includes that names and addresses of each stream. Then the gateway could mount the ConfigMap and read the configuration off disk. This would mean that the http-gateway would be scoped to a namespace, but that's probably good thing anyway.

Other protocol gateways could use the same ConfigMap down the road.

**Comment by ericbottard** [comment]
A couple of devil's advocate / anti-dogmatic questions:

> Then the gateway could mount the ConfigMap and read the configuration off disk.

Then how do we handle live changes to the CM? Do we provide a helper for that? Also, ConfigMap is the new data-plane in that approach. What does it buy us?

> the http-gateway would be scoped to a namespace, but that's probably good thing anyway.

Why? Also, who deploys the http-gateway then?

**Comment by scothis** [comment]
> Then how do we handle live changes to the CM? 

The content of the ConfigMap will be kept in sync by kubelet automatically

> Do we provide a helper for that?

https://golang.org/pkg/io/ioutil/#ReadFile

> Also, ConfigMap is the new data-plane in that approach. What does it buy us?

The ConfigMap is part of the control plane. The control plane needs to be able to reach into the data plane, the inverse is problematic.

> Why? Also, who deploys the http-gateway then?

The developer who wants to expose streams in the namespace they control

**Comment by ericbottard** [comment]
> The content of the ConfigMap will be kept in sync by kubelet automatically

That's not what I meant. I meant after **reading** the file. But you seem to imply that we / the-library should reload the file everytime.

> The ConfigMap is part of the control plane

Yes, sorry that's what I meant. Seems we've traded a memory-based-with-caching API for a file-based-always-reload API. Granted, the latter is more "down to earth" than the former, but it's just a shift of the boundary.

**Comment by scothis** [comment]
>  I meant after reading the file. But you seem to imply that we / the-library should reload the file everytime.

It's not a single file, but a file per stream. The file is on the tmpfs mount which is in memory, but you could add a cache since the address of the gateway for a given stream is unlikely to be volatile.

> it's just a shift of the boundary.

the location of that boundary is really important.
